### ISSUE TITLE
[Feature Request] Smart Boost Mode Handling

### ISSUE THREAD

**Issue by IBNobody** [retronx-team/sys-clk#18] opened 2020-03-15 16:04 UTC
Can sys-clk be tuned to better handle boost mode? When the Switch enters boost mode for loading (1785 CPU / 76 GPU), sys-clk resets the clocks to overridden values on the next polling interval.

Current behavior:

If I am overclocking at 1224 / 768 and enter a loading screen, the switch will jump to 1785 / 76 and then switch back to 1224 / 768.

Ideal Behavior: 

If I am overclocking at 1224 / 768 and enter a loading screen, the switch will jump to 1785 / 76. Sys-clk detects this and stops overriding the clock. When the CPU and GPU clocks change after exiting boost mode (CPU != 1785, GPU != 76), sys-clk should resume overriding tle clocks at 1224 / 768.

(My current work-around is to not overclock the CPU and to only overclock the GPU. This causes the CPU to boost up to 1785 but keeps the GPU at 768. Not ideal, but the title I am using it with is not GPU intensive during loading screens.)

**Comment by p-sam** [comment] 2020-03-15 16:17
Hey,

This is a duplicate of a discussion that went on in gbatemp multiple times:

References:
https://gbatemp.net/threads/sys-clk-under-overclocking-sysmodule.531372/page-28#post-8852404
https://gbatemp.net/threads/sys-clk-under-overclocking-sysmodule.531372/page-29#post-8866580

**Closed by p-sam** 2020-03-15 16:17 UTC

**Comment by IBNobody** [comment] 2020-03-15 17:03
So it's a conceptual denial, but not a technical one? (Meaning, if I fork and change how the line `if (hz != this->context->freqs[module] && this->context->enabled)`  handles boost mode, I could get it to work?)

**Comment by p-sam** [comment] 2020-03-15 17:20
Basically, discussion already happened in the links -> not worth the time

**Comment by IBNobody** [comment] 2020-03-15 18:45
I did check out the links, but what I saw was that this kind of change was
not in the spirit of the tool, and I didn't come across anything that said
that this wouldn't work.
