### ISSUE TITLE
sys-clk overlay crashes Atmosphere 0.18.0 under two conditions

### ISSUE THREAD

**Issue by jacoghi** [retronx-team/sys-clk#34] opened 2021-02-07 23:06 UTC
(This is regarding the overlay that comes bundled in this official package)
On the new Atmosphere 0.18.0, first boot:
*By default, modules are turned off.*

- Open Tesla menu on Atmosphere's first run, toggling sys-clk overlay ON and then trying to access the overlay results in a panic event from Atmosphere. This behavior did not happen on Atmosphere 0.17.1. The nro manager, however, can be used as expected without resulting in a crash.

- Every time the module is turned off under sysmodules, followed by the overlay trying to be accessed (resulting in a "fatal error, not running" as expected), going back to sysmodules and trying to turn it back ON results in a panic event from Atmosphere.

- The workaround is to have it marked for Auto-Start and never turn it back OFF. That being the case, a safer behavior would be to mark sys-clk overlay as a STATIC module instead of dynamic since as of now, its dynamic nature cannot be used without resulting in a crash. Both scenarios end up being basically the same, going from a cold, not auto started boot, to turning it on, and then crashing, however, happening when the user selects different options.

**Comment by p-sam** [comment] 2021-02-08 08:24
You should never try to kill the sys-clk sysmodule, doing so will skip cleaning up ressources and will prevent it from being turned back on. Right now, I'm using the overlay just fine on ams 0.18 and I could not reproduce your first scenario, so be sure to include the actual crash report, if you're not doing what I just mentioned.

 As for your third point, it sounds like your using it from some other packaged AIO bundle, because it's "marked for auto-start", with the boot2.flag file present in the release archive. The "static/dynamic" thing you're talking about is not related to stock Atmosphere or sys-clk, but rather your on/off sysmodule app and/or overlay.

**Comment by jacoghi** [comment] 2021-02-09 02:23
I'm using https://github.com/WerWolv/ovl-sysmodules which should be the official Tesla sys-modules toggler.
By first run I meant the first time you start Atmosphere, since all modules are turned off by default, toggling sys-clk using the abovementioned overlay results in a crash. I tested it with two SD card installations (although the same Switch) and it yielded a crash on both instances. BTW, when I describe first run to get the crash is by deleting all the files from my SD card except for the emuMMC folder and dropping the whole installation from scratch.

The static / dynamic thing comes from the ovl-sysmodules overlay and I assume there's a flag on the module that lets Tesla know if the module can be toggled dynamically (w/out a restart or statically). And no, I'm not using a pre-packaged bundle nor anything like that, this is for a manually put together package.

**Comment by p-sam** [comment] 2021-02-09 08:16
I know which overlay you're referring to, and the flag you're referring to is the `toolbox.json` config file. Since there's none in the official release, sys-clk should not even be listed in the overlay you use to spawn/kill sysmodules, which tells me you've created it yourself or got it from elsewhere. ( see https://github.com/WerWolv/ovl-sysmodules/blob/master/source/gui_main.cpp#L42 )

Closing the issue due to the lack of a crash report file when run at boot

**Closed by p-sam** 2021-02-09 08:16 UTC

**Comment by jacoghi** [comment] 2021-02-09 18:59
Logs were posted here when I figured this was an atmosphere issue.

https://github.com/Atmosphere-NX/Atmosphere/issues/1358

https://drive.google.com/file/d/1s5O3eskrIg7dvG9ZbPZoVGcHPutuYiGn/view?usp=sharing

So the simple fact you drop a ovl file into the overlays folder is not enough for the sysmodules overlay to list it after reading it at boot time? Is this flag mandatory for the module to be listed? One log was due to emuiibo crashing which turned out to be due to this sm extension as pointed out by SciresM. If these are not the logs you're talking about, let me know and I'll get them for you.
