### ISSUE TITLE
Mariko GPU locked to 460 in handheld

### ISSUE THREAD

**Issue by Thorhax** [retronx-team/sys-clk#70] opened 2023-10-16 11:40 UTC
My understanding is that Mariko should be able to hit 614mhz on handheld however my unit on the latest ams and sys-clk doesn't allow for anything over 460 unless a charger is connected.

Also I would really appreciate an option to enable unsafe frequencies like sys-clk-oc has. Since I undervolt and keep voltages and clockspeeds in check manually.

**Comment by hanai3Bi** [comment] 2023-10-16 11:45
the bug is caused by missing 'break' in sku type check

**Comment by p-sam** [comment] 2023-10-16 12:17
Fixed as of last commit, prerelease binaries were updated. I'll leave the issue open until the proper release

> Also I would really appreciate an option to enable unsafe frequencies like sys-clk-oc has. Since I undervolt and keep voltages and clockspeeds in check manually.
See https://github.com/retronx-team/sys-clk/issues/10 and the #oc-discussion channel you're regularly in on Discord for potential answers

**Closed** 2024-10-12 10:06 UTC
